config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resources :users
  resources :orders, only: [:index, :show, :create, :update, :destroy]

  resources :products do
    resources :comments
  end

  mount ActionCable.server => '/cable'

  # You can have the root of your site routed with "root"
  root 'static_pages#index'

  get '/search', to: 'static_pages#search'

  get '/search_results', to: 'products#search_results'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  post '/thank_you', to: 'static_pages#thank_you'

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get '/profile', to: 'devise/registrations#edit'
  end

  # Stripe credit card payments - payments controller
  post '/payments/create', to: 'payments#create'
  get 'payments/payment_thank_you', to: 'payments#payment_thank_you'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :orders

  validates :first_name, :last_name, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  respond_to :json, :html

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order("created_at DESC")
    respond_with @users
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User has been created successfully.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User has been updated successfully.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User has been deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="user-form">

  <%= render partial: "shared/users_error" %>

  <%= form_for(@user) do |f| %>

    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
    <div class="actions">
      <%= submit_tag "Submit", class: "btn btn-primary" %>
    </div>

  <% end %><!-- end of form_for -->

  <%= link_to "Return to Profile", '/profile', class: "btn btn-md btn-navigate" %>
</div>

app/views/users/edit.html.erb
<div class="users-jumbotron">
  <div class="container">
    <h1 id="static-header">Edit User Info</h1>
  </div>
</div>

<%= render partial: "shared/notice_alert" %>

<div class="users-container">
  <%= render 'form' %>
</div>

<div class="extra-space"></div>

app/views/users/index.html.erb
<div class="users-jumbotron">
  <div class="container">
    <h1 id="static-header">List of Users</h1>
  </div>
</div>

<%= render partial: "shared/notice_alert" %>

<div class="users-container">

  <p>Here are all registered users:</p>
  <br>

  <div class="users">

    <table class="table table-hover">
      <thead>
        <tr>
          <th>User ID</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Email</th>
          <th></th>
          <th colspan="3">Options</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td></td>
            <td><%= link_to ('<span class="glyphicon glyphicon-user" aria-hidden="true"></span>').html_safe, user, class: "btn btn-primary btn-sm", title: "Show" %></td>
            <td><%= link_to ('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>').html_safe, edit_user_path(user), class: "btn btn-warning btn-sm", title: "Edit" %></td>
            <td><%= link_to ('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>').html_safe, user, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div><!-- end of .users -->

</div><!-- end of .users-container -->

<div class="extra-space"></div>

app/views/users/new.html.erb
<div class="users-jumbotron">
  <div class="container">
    <h1 id="static-header">New User</h1>
  </div>
</div>

<%= render partial: "shared/notice_alert" %>

<div class="container users-container">

  <%= render 'form' %>

  <%= link_to 'Back', users_path, class: "btn btn-navigate" %>

</div>

app/views/users/show.html.erb
<div class="users-jumbotron">
  <div class="container">
    <h1 id="static-header">Show User Info</h1>
  </div>
</div>

<%= render partial: "shared/notice_alert" %>

<div class="container users-container">

  <p>
    <strong>User ID:</strong>
    <%= @user.id %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= @user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <%= link_to "Return", users_path, class: "btn btn-md btn-primary" %>

</div>

<div class="extra-space"></div>