config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resources :users
  resources :orders, only: [:index, :show, :create, :update, :destroy]

  resources :products do
    resources :comments
  end

  mount ActionCable.server => '/cable'

  # You can have the root of your site routed with "root"
  root 'static_pages#index'

  get '/search', to: 'static_pages#search'

  get '/search_results', to: 'products#search_results'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  post '/thank_you', to: 'static_pages#thank_you'

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get '/profile', to: 'devise/registrations#edit'
  end

  # Stripe credit card payments - payments controller
  post '/payments/create', to: 'payments#create'
  get 'payments/payment_thank_you', to: 'payments#payment_thank_you'

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

  validates :title, :author, :price, :image_url, presence: true
  validates :price, numericality: true

  def average_rating
    comments.average(:rating).to_f
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    respond_with @products
  end

  # Product search
  def search_results
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @products = Product.where("title ilike :search or author ilike :search or description ilike :search", {search: "%#{search_term}%"})
      else
        @products = Product.where("title like :search or author like :search or description like :search", {search: "%#{search_term}%"})
      end
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    # Links to previous and next products on show page
    @previous = Product.where("id < ?", params[:id]).order(:id).first   
    @next = Product.where("id > ?", params[:id]).order(:id).first
    # Comments pagination with will_paginate gem
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product has been created successfully.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product has been updated successfully.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product has been deleted successfully.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :author, :description, :image_url, :price)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count           = Product.count
    max_updated_at  = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end

end

app/views/products/_comments.html.erb
<div class="product-comment-form">
  <% @comments.each do |comment| %>
    <div class="row comment-row">
      <p>
        <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        <!-- Admin can delete comments -->
        <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' }, id: "comment-delete" %>
        <% end %>
      </p>
      <!-- Raty plugin star rating -->
      <p><div class="rated" data-score="<%= comment.rating %>"></div></p>
      <p><%= comment.body %></p>
      <hr>
    </div><!-- end of .comment-row -->
  <% end %>

  <!-- will_paginate pagination for comments -->
  <div class="digg_pagination">
    <%= will_paginate @comments %>
  </div>

</div>

app/views/products/_form.html.erb
<%= render partial: "shared/products_error" %>

<%= form_for(@product) do |f| %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-md btn-primary" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="review-form">
  <!-- User can write review if signed in -->
  <% if signed_in? %>
    <h3>Review this book</h3>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <p>
        <%= f.label :body, "Your Review" %><br>
        <%= f.text_area :body, class: "form-control" %>
      </p>
      <p>
        <%= f.label :rating, "Your Rating" %><br>
        <div class="rating"></div>
      </p>
      <br>
      <p>
        <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
      </p>
    <% end %><!-- end of form_for -->
  <% end %><!-- end of signed_in? -->
</div>

app/views/products/_product.html.erb
<div class="col-md-4 col-sm-6 col-xs-12 product-box">

  <% cache product do %><!-- start of product caching -->

  <div class="book">
    <!-- Title div automatically resized by JS -->
    <div class="product-title">
      <h2><%= product.title %></h2>
    </div>
    <div class="thumbnail"><%= link_to image_tag(product.image_url, class: "img-responsive"), product %></div>
    <div class="book-info">
      <!-- Author div automatically resized by JS -->
      <div class="product-author">
        <p>By <%= product.author %></p>
      </div>
      <p>$<%= product.price %></p>
    </div>
  </div>

  <% end %><!-- end of product caching -->

</div>

app/views/products/edit.html.erb
<%= image_tag("books_products.jpg", class: "img-responsive") %>
<h1>Edit Product</h1>

<%= render partial: "shared/notice_alert" %>

<div class="edit-product-container">
  <%= render 'form' %>

  <%= link_to 'Back', products_path, class: "btn btn-navigate" %>

</div>

app/views/products/index.html.erb
<div class="products-index-jumbotron">
  <div class="container">
    <h1 id="static-header">Our Books</h1>
  </div>
</div>

<%= render partial: "shared/notice_alert" %>

<div class="container product-index-container">
  <h3 id="products-subtitle">Here is a selection of the books that we currently have in our inventory.</h3>

  <div class="product-container">
    <div class="row product-row">

      <% cache(cache_key_for_products) do %><!-- start of products caching -->
        <%= render @products %>
      <% end %><!-- end of products caching -->

    </div>
  </div>

  <!-- Admin can manually add new product -->
  <% if signed_in? && current_user.admin? %>
    <div>
      <%= link_to 'Add New Product', new_product_path, class: "btn btn-navigate" %>
    </div>
  <% end %>

</div>

<div class="extra-space"></div>

app/views/products/new.html.erb
<%= image_tag("pics/books_products.jpg", class: "img-responsive") %>
<h1>Add New Book</h1>

<%= render partial: "shared/notice_alert" %>

<div class="new-product-container">

  <% if signed_in? && current_user.admin? %>
    <%= render 'form' %>
  <% end %>

  <%= link_to 'Back', products_path, class: "btn btn-navigate" %>
</div>

app/views/products/search_results.html.erb
<div class="products-search-jumbotron">
  <div class="container">
    <h1 id="static-header">Your Search</h1>
  </div>
</div>

<%= render partial: "shared/notice_alert" %>

<div class="book-search">
  <div class="container product-container">
    <div class="row product-row">
      <% if @products.present? %>
        <p>Here are the results of your search for "<%= params[:q] %>":</p><!-- Display product search results -->
        <%= render @products %>
      <% else %>
        <p>Sorry, there are books containing "<%= params[:q] %>".</p><!-- No search results -->
      <% end %>
    </div><!-- end of .product-row -->
  </div><!-- end of .product-container -->
</div>

<%= link_to 'Back to Search', '/search', class: "btn btn-navigate", id: "btn-search-back" %>

<div class="extra-space"></div>

app/views/products/show.html.erb
<div class="products-index-jumbotron"></div>

  <h1><%= @product.title %></h1>

  <%= render partial: "shared/notice_alert" %>

  <% cache @product do %><!-- start of product caching -->

  <div class="container show-container">
    <div class="row show-product-row" data-product-id="<%= @product.id %>">
      <div class="col-md-4">
        <%= image_tag(@product.image_url, width: "190", class: "img-responsive img-zoom", id: "show-product-image", data_zoom_image: @product.image_url) %>
      </div>

      <div class="col-md-6", id="show-product-info">
        <p>
          <strong>Title:</strong>
          <%= @product.title %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= @product.author %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @product.description %>
        </p>

        <p>
          <strong>Price:</strong>
          $<%= @product.price %>
        </p>

        <!-- Payment button appears if user signed in -->
        <% if signed_in? %>
          <%= form_tag "/payments/create" do %>
            <%= render partial: "shared/stripe_checkout_button" %>
            <%= hidden_field_tag(:product_id, @product.id) %>
          <% end %>
        <% end %>

        <div class="product-comments">
          <!-- Overall product rating with Raty plugin -->
          <p class="overall-rating"><b>Overall Rating:</b><div class="rated overall-rating" id="overall-star-rating" data-score="<%= @product.average_rating %>"></div></p>
          <p><b>Others Have Said:</b></p>
          <!-- ActionCable new comment post notification -->
          <div class="alert alert-posting" style="display:none" role="alert">A new comment has been posted!</div>
            <!-- All user comments (reviews) -->
            <%= render 'comments' %>
            <!-- New comment form -->
            <%= render 'new_comment' %>
        </div>

        <!-- Admin can manually edit or delete product -->
        <% if signed_in? && current_user.admin? %>
          <div class="edit-delete-links">
            <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-edit-delete" %>
            <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-edit-delete" %>
          </div>
        <% end %>

    </div><!-- end of .show-product-row -->
  </div><!-- end of .show-container -->

  <% end %><!-- end of product caching -->

    <%= link_to 'Back to Products', products_path, class: "btn btn-navigate" %>
  	
    <div class="show-browse-links">
      <p><%= link_to '< Previous Book', @previous, class: "btn btn-show-browse" %></p>
      <p><%= link_to 'Next Book >', @next, class: "btn btn-show-browse" %></p>
    </div>

</div><!-- end of .products-index-jumbotron -->

<div class="extra-space"></div>