config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :registrations => "user_registrations" }
  resources :users
  resources :orders, only: [:index, :show, :create, :update, :destroy]

  resources :products do
    resources :comments
  end

  mount ActionCable.server => '/cable'

  # You can have the root of your site routed with "root"
  root 'static_pages#index'

  get '/search', to: 'static_pages#search'

  get '/search_results', to: 'products#search_results'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  post '/thank_you', to: 'static_pages#thank_you'

  devise_scope :user do
    get '/sign_up', to: 'devise/registrations#new'
    get '/profile', to: 'devise/registrations#edit'
  end

  # Stripe credit card payments - payments controller
  post '/payments/create', to: 'payments#create'
  get 'payments/payment_thank_you', to: 'payments#payment_thank_you'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-links">
      <p><a href="#">Terms &amp; Conditions</a> | <a href="#">Legal Information</a></p>
      <p><a href="#">Impressum</a> | <a href="#">Return Policy</a></p>
      <p>&copy; 2016, Oasis Books, Inc.</p>
    </div>

    <div class="socia-media-links">
      <p>Connect with us on</p>

      <a class="btn btn-social-icon btn-facebook">
        <span class="fa fa-facebook"></span>
      </a>

      <a class="btn btn-social-icon btn-twitter">
        <span class="fa fa-twitter"></span>
      </a>

      <a class="btn btn-social-icon btn-pinterest">
        <span class="fa fa-pinterest"></span>
      </a>

      <a class="btn btn-social-icon btn-tumblr">
        <span class="fa fa-tumblr"></span>
      </a>
    </div>

  </div><!-- end of .container -->
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>Oasis Books</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/981382a342.js"></script>
  <%= action_cable_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Christian McTighe">
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-transparent navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation-bar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="navbar-collapse collapse" id="navigation-bar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "scroll-nav" %></li>
        <li><%= link_to "Products", products_path, class: "scroll-nav" %></li>
        <li><%= link_to "Search", '/search', class: "scroll-nav" %></li>
        <li><%= link_to "About", '/about', class: "scroll-nav" %></li>
        <li><%= link_to "Contact", '/contact', class: "scroll-nav" %></li>
        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to "View Orders", orders_path, class: "scroll-nav" %></li>
          <li><%= link_to "View Users", users_path, class: "scroll-nav" %></li>
          <li><%= link_to("My Profile", '/profile', class: "scroll-nav") %></li>
          <li><%= link_to("Logout", destroy_user_session_path, :method => :delete, class: "scroll-nav") %></li>
        <% elsif user_signed_in? %>
          <li><%= link_to "My Orders", orders_path, class: "scroll-nav" %></li>
          <li><%= link_to("My Profile", '/profile', class: "scroll-nav") %></li>
          <li><%= link_to("Logout", destroy_user_session_path, :method => :delete, class: "scroll-nav") %></li>
        <% else %>
          <li><%= link_to "Sign Up", '/sign_up', class: "scroll-nav" %></li>
          <li><%= link_to("Login", new_user_session_path, class: "scroll-nav") %></li>
        <% end %>
      </ul>
    </div>
  </div><!-- end of .container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>

    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body class="devise-background">

    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>

</html>